##动态权限配置文件
#List<Map<String, String>>
permission-config:
  perms:
    - url: /cat
      permission: roles[cat]
    - url: /dog
      permission: roles[dog]
    - url: /sing
      permission: perms[sing]
    - url: /jump
      permission: perms[jump]
    - url: /rap
      permission: perms[rap]
    - url: /basketball
      permission: perms[basketball]


# redis集群配置
spring:
  redis:
    jedis:
      pool:
        max-idle: 100  #连接池中的最大空闲连接
        max-total: 1000   #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
        max-wait-millis: 1000   #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-evictable-idle-time-millis: 300000   #连接的最小空闲时间 默认1800000毫秒(30分钟)
        num-tests-per-eviction-run: 1024   #每次释放连接的最大数目,默认3
        time-between-eviction-runs-millis: 3000   #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
        test-on-borrow: true   #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
        test-while-idle: true    #在空闲时检查有效性, 默认false
      timeout: 100000        #连接超时时间（毫秒）

      cluster:
        nodes: 192.168.20.202:8011,192.168.20.202:8012,192.168.20.202:8013,192.168.20.202:8014,192.168.20.202:8015,192.168.20.202:8016
        max:
          attempts: 3
